version: '3.9'
services:
  lsmith:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.lite
    ports:
      - 8000:8000
    volumes:
      - ./docker-data/models:/app/models
      - ./docker-data/outputs:/app/outputs
    environment:
      - COMMANDLINE_ARGS=
      - UVICORN_ARGS=--host 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]